
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app

  gen:
    dao:
    # If in docker container, we should use
    # database rather than localhost
    # - link: "sqlite::@file(./manifest/database/SQLite/overflows.db)"
    - link: "pgsql:overflower:Passw0rd@tcp(localhost:5432)/overflows"
      tablesEx: "casbin_rule, atlas_schema_revisions, sqlite_sequence"

  run:
    path:  "bin"
    args:  "--mode=server"

  build:
    name: "overflows"
    arch: "amd64"
    system: "windows"
    packSrc: "resource/public/www, manifest/config/config.yaml"
    output: "./temp/overflows.exe"
    dumpEnv: false
    extra: "-ldflags=\"-H windowsgui\""

  # build:
  #   name: "overflows"
  #   arch: "amd64"
  #   system: "linux"
  #   packSrc: "resource/public/www, manifest/config/config.yaml"
  #   output: "./temp/overflows"
  #   dumpEnv: false
  #   cgo: true