server:
  address:          ":8000"
  openapiPath:      "/api.json"
  swaggerPath:      "/swagger"
  graceful:         true
  gracefulTimeout:  10
  logStdout:        false
  errorLogEnabled:  false
  accessLogEnabled: false
  DumpRouterMap:    false

database:
  logger:
    path:           "./.overflows_log"
    file:           "database-{Y-m-d}.log"
    level :         "all"
    stdout:         true
  standaloneMode:
    link:           "sqlite::@file(./overflows.db)"
    role:           "master"
  serverMode:
    link:           "pgsql:overflower:Passw0rd@tcp(localhost:5432)/overflows"
    role:           "master"

logger:
  path:             "./.overflows_log"
  level :           "all"
  stdout:           true