server:
  address:          ":8000"
  openapiPath:      "/api.json"
  swaggerPath:      "/swagger"
  graceful:         true
  gracefulTimeout:  10
  logStdout:        false
  errorLogEnabled:  false
  accessLogEnabled: false
  DumpRouterMap:    false

database:
  logger:
    path:           "./Overflows_log"
    file:           "database-{Y-m-d}.log"
    level :         "all"
    stdout:         true
  standaloneMode:
    link:           "sqlite::@file(/var/data/db.sqlite3)"
    role:           "master"
  serverMode:
    link:           "pgsql:overflower:Passw0rd@localhost:5432/overflows?sslmode=disable"
    role:           "master"

logger:
  path:             "./Overflows_log"
  level :           "all"
  stdout:           true