import * as MDIIcons from '@mdi/js';

const MDIAliases = {
    eye: MDIIcons.mdiEye,
    eyeOff: MDIIcons.mdiEyeOff,
    keyboardBackspace: MDIIcons.mdiKeyboardBackspace,
    dotsHorizontal: MDIIcons.mdiDotsHorizontal,
    image: MDIIcons.mdiImage,
    weatherSunny: MDIIcons.mdiWeatherSunny,
    weatherNight: MDIIcons.mdiWeatherNight,
    translate: MDIIcons.mdiTranslate,
    text: MDIIcons.mdiText,
    web: MDIIcons.mdiWeb,
    refresh: MDIIcons.mdiRefresh,
    cogOutline: MDIIcons.mdiCogOutline,
    trashCanOutline: MDIIcons.mdiTrashCanOutline,
    arrowDownBoldBoxOutline: MDIIcons.mdiArrowDownBoldOutline,
    arrowUpBoldBoxOutline: MDIIcons.mdiArrowUpBoldOutline,
    arrowLeft: MDIIcons.mdiArrowLeft,
    arrowRight: MDIIcons.mdiArrowRight,
    arrowUp: MDIIcons.mdiArrowUp,
    arrowDown: MDIIcons.mdiArrowDown,
    deleteForeverOutline: MDIIcons.mdiDeleteForeverOutline,
    helpCircleOutline: MDIIcons.mdiHelpCircleOutline,
    animation: MDIIcons.mdiAnimation,
    lockOpenVariantOutline: MDIIcons.mdiLockOpenVariantOutline,
    lockOutline: MDIIcons.mdiLockOutline,
    informationOutline: MDIIcons.mdiInformationOutline,
    boxShadow: MDIIcons.mdiBoxShadow,
    formatClear: MDIIcons.mdiFormatClear,
    formatItalic: MDIIcons.mdiFormatItalic,
    formatAlignLeft: MDIIcons.mdiFormatAlignLeft,
    formatAlignCenter: MDIIcons.mdiFormatAlignCenter,
    formatAlignRight: MDIIcons.mdiFormatAlignRight,
    formatAlignJustify: MDIIcons.mdiFormatAlignJustify,
    formatUnderline: MDIIcons.mdiFormatUnderline,
    formatOverline: MDIIcons.mdiFormatOverline,
    formatStrikethrough: MDIIcons.mdiFormatStrikethrough,
    plusCircleOutline: MDIIcons.mdiPlusCircleOutline,
    google: MDIIcons.mdiGoogle,
    github: MDIIcons.mdiGithub,
    wechat: MDIIcons.mdiWechat,
    qq: MDIIcons.mdiQqchat,
    chevronRight: MDIIcons.mdiChevronRight,
    chevronLeft: MDIIcons.mdiChevronLeft,
    check: MDIIcons.mdiCheck,
    drawPen: MDIIcons.mdiDrawPen,
    xml: MDIIcons.mdiXml,
    cloudRefreshVariant : MDIIcons.mdiCloudRefreshVariant,
    fileSend : MDIIcons.mdiFileSend,
    accountCircle: MDIIcons.mdiAccountCircle,
    cloudAlertOutline: MDIIcons.mdiCloudAlertOutline,
    cloudCheckOutline: MDIIcons.mdiCloudCheckOutline,
    cloudUploadOutline: MDIIcons.mdiCloudUploadOutline,
}
export default MDIAliases