name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Set up GF
        run: |
          wget -O gf "https://github.com/gogf/gf/releases/latest/download/gf_$(go env GOOS)_$(go env GOARCH)" &&
          chmod +x gf &&
          ./gf install -y &&
          rm ./gf
      
      - name: Set up env
        run: |
          export CGO_ENABLED=1 &&
          sudo apt-get install -y build-essential pkg-config libappindicator3-dev gcc

      - name: Build
        run: gf build main.go -n gf -a all -s all -p temp

      - name: Move Files Before Release
        run: |
          cd temp
          for OS in *;do for FILE in $OS/*;\
          do if [[ ${OS} =~ 'windows' ]];\
          then mv $FILE overflows_$OS.exe && rm -rf $OS;\
          else mv $FILE overflows_$OS && rm -rf $OS;\
          fi;done;done

      - name: Create Github Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:     ${{ github.ref }}
          name: Overflows Release ${{ github.ref }}
          draft:        false
          prerelease:   false
      
      - name: Upload Release Asset
        id:   upload-release-asset
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["temp/overflows_*"]'
